apiVersion: apps/v1
kind: Deployment
metadata:
  name: larawel-frontend
  labels:
    app: larawel
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: larawel
  template:
    metadata:
      labels:
        app: larawel
    spec:
      containers:
      - name: larawel
        image: 766822611343.dkr.ecr.us-east-1.amazonaws.com/laraeks:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
