name: Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # SSH into the server, pull code, build Docker image, and push to ECR
    - name: SSH into Server and Build Docker Image
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 52.91.201.67
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Correctly reference the SSH private key secret
        script: |
          # Switch to root user using sudo su -
          sudo su - << 'EOF'

          # Navigate to the correct directory where the Dockerfile is located
          cd /root/LarawelTask1

          # Ensure Git is initialized
          git fetch --all
          git checkout main
          git pull origin main

          # Ensure Docker is installed and the user has permission to use Docker
          usermod -aG docker ubuntu
          systemctl restart docker

          # Build the Docker image
          REPO_URI=766822611343.dkr.ecr.us-east-1.amazonaws.com/laraeks
          docker build -t $REPO_URI:latest .

          # Log in to Amazon ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URI

          # Push the Docker image to ECR
          docker push $REPO_URI:latest

          EOF

    # Set up Kubernetes Kubeconfig
    - name: Set up Kubeconfig for Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}

    # Deploy to Kubernetes
    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 52.91.201.67
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the same SSH private key secret here
        script: |
          # Switch to root user using sudo su -
          sudo su - << 'EOF'

          # Apply Kubernetes manifests from the specified directory
          kubectl apply -f /root/LarawelTask1/k8s-manifest/frontend/deployment.yml

          # Optionally, restart the deployment (if necessary)
          kubectl rollout restart deployment/frontend  # Replace with your actual deployment name

          EOF
